# -*- coding: utf-8 -*-
"""News

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsafRUZo09b50G0GgfVBAzwaWieBckby
"""

#본문 가져오기
!pip install newspaper3k lxml_html_clean
from newspaper import Article

#유사도
!pip install transformers torch
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

model_name = "BAAI/bge-reranker-v2-m3"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
model.eval()

#본문 가져오기
def bring_article(url):
    article_obj = Article(url, language='ko')
    article_obj.download()
    article_obj.parse()

    title = article_obj.title
    article = article_obj.text

    return title, article

#유사도
def similarity_check(summary, title):
    inputs = tokenizer(
        summary,
        title,
        padding=True,
        truncation=True,
        return_tensors="pt",
        max_length=512,
    )

    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits.squeeze(-1)
        score = torch.sigmoid(logits).item()

    similarity = round(score, 4)
    return similarity

"""함수 이름: similarity_check

들어가는 변수(class): summary(str), title(str)

나오는 변수(class): similarity(float)

0~1 사이로 소수점 넷째 자리까지 출력

---

함수 이름: bring_article

들어가는 변수(class): url(str)

나오는 변수(class): title(str), article(str)


"""

url = input("기사 URL을 입력하세요: ")
title, article = bring_article(url)

# 1. 라이브러리 설치
!pip install gradio

import gradio as gr

# 2. 핵심 기능을 담당할 파이썬 함수 작성
def greet(name):
    return f"안녕하세요, {name}님! 코랩에서 만든 웹페이지입니다."

# 3. 웹 인터페이스 생성 및 실행
demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch(share=True) # share=True 옵션이 공개 웹 링크를 만들어줍니다.